apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2023-11-13T07:02:19Z"
  generateName: csi-csi-secrets-store-provider-azure-
  labels:
    app: csi-secrets-store-provider-azure
    app.kubernetes.io/instance: csi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: csi-secrets-store-provider-azure
    app.kubernetes.io/version: 1.4.1
    controller-revision-hash: 795fbfdbcb
    helm.sh/chart: csi-secrets-store-provider-azure-1.4.4
    pod-template-generation: "1"
  name: csi-csi-secrets-store-provider-azure-rfg8w
  namespace: azdevspace
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: csi-csi-secrets-store-provider-azure
    uid: fc322b09-8413-4ad9-b369-12fd2050542d
  resourceVersion: "2029882"
  uid: 06922115-1ddf-4b68-8524-6d52b5aa1bab
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - aks-agentpool-33258612-vmss00000b
  containers:
  - args:
    - --endpoint=unix:///provider/azure.sock
    - --construct-pem-chain=true
    - --healthz-port=8989
    - --healthz-path=/healthz
    - --healthz-timeout=5s
    image: mcr.microsoft.com/oss/azure/secrets-store/provider-azure:v1.4.1
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: 8989
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 10
    name: provider-azure-installer
    ports:
    - containerPort: 8898
      hostPort: 8898
      name: metrics
      protocol: TCP
    resources:
      limits:
        cpu: 50m
        memory: 100Mi
      requests:
        cpu: 50m
        memory: 100Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /provider
      name: provider-vol
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-7s4cb
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: csi-secrets-store-provider-azure
  serviceAccountName: csi-secrets-store-provider-azure
  terminationGracePeriodSeconds: 30
  tolerations:
  - operator: Exists
  volumes:
  - hostPath:
      path: /var/run/secrets-store-csi-providers
      type: ""
    name: provider-vol
  - name: kube-api-access-7s4cb
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-11-13T07:02:19Z"
    message: '0/9 nodes are available: 1 Insufficient cpu. preemption: 0/9 nodes are
      available: 9 No preemption victims found for incoming pod..'
    reason: Unschedulable
    status: "False"
    type: PodScheduled
  phase: Pending
  qosClass: Guaranteed
