apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aad-role-binding
  namespace: azdevspace
subjects:
- kind: User
  name: "zepor"  # Use the managed identity name
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: Azure Kubernetes Fleet Manager RBAC Cluster Admin  # Replace with the actual role name
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sp-deployment-manager
  namespace: azdevspace
subjects:
- kind: User
  name: "b7d95cfe-542a-4116-ae52-c64bf13ded90"  # The application ID of the Service Principal
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin  # Using the built-in 'admin' ClusterRole
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sp-rolebinding
  namespace: azdevspace
subjects:
- kind: User
  name: "b7d95cfe-542a-4116-ae52-c64bf13ded90"  # Application ID of the service principal
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit  # or another role that provides necessary permissions
  apiGroup: rbac.authorization.k8s.io

