trigger:
  branches:
    include:
      - KaggleNFL2025
    exclude:
      - azure-pipelines

pool:
  name: 'Ubuntu-latest'

variables:
  TARGET_BRANCH: 'azure-pipelines'  # Target branch on GitHub

steps:
  - checkout: self
    persistCredentials: true

  # Verify Python installation
  - script: |
      python3 --version
      which python3
    displayName: 'Verify Python Version'
 
  # Configure Git settings for pushing to GitHub
  - script: |
      git config --global user.name "Azure Pipelines"
      git config --global user.email "$(EMAIL)"  # Replace with your email

  # Force push changes to GitHub target branch (azure-pipelines)
  - script: |
      git push --force origin HEAD:$(TARGET_BRANCH)
    displayName: 'Push changes to GitHub'
