trigger:
  branches:
    include:
      - KaggleNFL2025  # The branch in Azure DevOps that triggers the pipeline

pool:
  name: 'Ubuntu-latest'  # Use your self-hosted agent pool name

variables:
  TARGET_BRANCH: 'azure-pipelines'  # Target branch on GitHub

steps:
  - checkout: self

  # Verify Python installation
  - script: |
      python3 --version
      which python3
    displayName: 'Verify Python Version'
    
  # Configure Git settings for GitHub push
  - script: |
      git config --global user.name "$USERNAME"
      git config --global user.email "$EMAIL"
    env:
      USERNAME: $(USERNAME)  # Ensure these are set as pipeline secrets
      EMAIL: $(EMAIL)

  # Push changes to GitHub target branch (azure-pipelines)
  - script: |
      git remote add github https://$USERNAME:$GITHUB_TOKEN@github.com/$USERNAME/$GITHUB_REPO.git || echo "Remote already exists"
      git push github HEAD:$(TARGET_BRANCH)  # Push current changes to azure-pipelines on GitHub
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)
      USERNAME: $(USERNAME)
      GITHUB_REPO: $(GITHUB_REPO)
    displayName: 'Push changes to GitHub'
