trigger:
  branches:
    include:
      - KaggleNFL2025  # The branch in Azure DevOps that triggers the pipeline

pool:
  name: 'Ubuntu-latest'  # Use your self-hosted agent pool name

variables:
  TARGET_BRANCH: 'azure-pipelines'  # Target branch on GitHub

steps:
  - checkout: self
    # Link the GitHub service connection for OAuth authentication
    persistCredentials: true

  # Verify Python installation
  - script: |
      python3 --version
      which python3
    displayName: 'Verify Python Version'
 
  # Configure Git settings for pushing to GitHub
  - script: |
      git config --global user.name "Azure Pipelines"
      git config --global user.email "$(EMAIL)"  # Replace with your email

  # Push changes to GitHub target branch (azure-pipelines)
  - script: |
      git push origin HEAD:$(TARGET_BRANCH)
    displayName: 'Push changes to GitHub'
