trigger:
  branches:
    include:
      - KagleNFL2025  # or your primary branch

pool:
  name: 'Ubuntu-latest'  # Replace with the name of your self-hosted agent pool

variables:
  GITHUB_TOKEN: $(GITHUB_TOKEN)          
  USERNAME: $(USERNAME)  
  EMAIL: $(EMAIL)       
  GITHUB_REPO: $(GITHUB_REPO) 

steps:
  - checkout: self

  # Verify that Python is available
  - script: |
      python3 --version
      which python3
    displayName: 'Verify Python Version'
    
  # Configure git settings for GitHub push
  - script: |
      git config --global user.name "$(USERNAME)"
      git config --global user.email "$(EMAIL)" 
    env:
      USERNAME: $(USERNAME)
      EMAIL: $(EMAIL)

  # Push changes to GitHub
  - script: |
      git remote add github https://$(USERNAME):$(GITHUB_TOKEN)@github.com/$(USERNAME)/$(GITHUB_REPO).git
      git push github azure-pipelines
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)
    displayName: 'Push changes to GitHub'
