trigger:
  branches:
    include:
      - KaggleNFL2025  # The primary branch in Azure DevOps

pool:
  name: 'Ubuntu-latest'  # This matches the custom pool name for your self-hosted agent

variables:
  TARGET_BRANCH: 'azure-pipelines'  # The target branch on GitHub

steps:
  - checkout: self

  # Verify Python installation
  - script: |
      python3 --version
      which python3
    displayName: 'Verify Python Version'
    
  # Configure Git settings for GitHub push
  - script: |
      git config --global user.name "$USERNAME"
      git config --global user.email "$EMAIL"
    env:
      USERNAME: $(USERNAME)  # These should be set as pipeline secrets in Azure DevOps
      EMAIL: $(EMAIL)

  # Ensure the KaggleNFL2025 branch exists and check it out
  - script: |
      git fetch origin KaggleNFL2025  # Fetch the branch from origin
      git checkout KaggleNFL2025 || echo "Branch KaggleNFL2025 not found" 
    displayName: 'Fetch and Checkout KaggleNFL2025 Branch'

  # Push changes to the target GitHub branch
  - script: |
      git remote add github https://$USERNAME:$GITHUB_TOKEN@github.com/$USERNAME/$GITHUB_REPO.git || echo "Remote already exists"
      git push github KaggleNFL2025:$(TARGET_BRANCH)  # Push KaggleNFL2025 branch in ADO to azure-pipelines on GitHub
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)
      USERNAME: $(USERNAME)
      GITHUB_REPO: $(GITHUB_REPO)
    displayName: 'Push changes to GitHub'
