trigger:
  branches:
    include:
      - KaggleNFL2025  # Your primary branch in Azure DevOps

pool:
  name: 'Ubuntu-latest'  # Replace with the name of your self-hosted agent pool

variables:
  TARGET_BRANCH: 'azure-pipelines'  # Target branch on GitHub

steps:
  - checkout: self

  # Verify that Python is available
  - script: |
      python3 --version
      which python3
    displayName: 'Verify Python Version'
    
  # Configure git settings for GitHub push
  - script: |
      git config --global user.name "$USERNAME"
      git config --global user.email "$EMAIL"
    env:
      USERNAME: $(USERNAME)  # Ensure these variables are set in your Azure DevOps pipeline settings or secret variables
      EMAIL: $(EMAIL)

  # Fetch all branches and explicitly checkout KaggleNFL2025
  - script: |
      git fetch origin
      if git rev-parse --verify origin/KaggleNFL2025; then
        git checkout -B KaggleNFL2025 origin/KaggleNFL2025
      else
        echo "Branch KaggleNFL2025 not found on origin. Please ensure it exists and is spelled correctly."
        exit 1
      fi
    displayName: 'Fetch and Checkout KaggleNFL2025 Branch'

  # Push changes to GitHub target branch (azure-pipelines)
  - script: |
      git remote add github https://$USERNAME:$GITHUB_TOKEN@github.com/$USERNAME/$GITHUB_REPO.git || echo "Remote already exists"
      git push github KaggleNFL2025:$(TARGET_BRANCH)  # Push KaggleNFL2025 branch to azure-pipelines on GitHub
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)
      USERNAME: $(USERNAME)
      GITHUB_REPO: $(GITHUB_REPO)
    displayName: 'Push changes to GitHub'
