version: '3.7'
networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
volumes:
  combined:
    external: true
  redis_data:
services:
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis_data:/data
    networks:
      - mynetwork
    ports:
      - 6379:6379
  combined_app:
    build:
      context: .
      dockerfile: Dockerfile.python
    image: python:3.9.18
    container_name: nflapp
    ports:
      - 5000:5000 
    volumes:
      - ~/Website2/src:/Website2/src
      - ~/Website2/Secrets:/Website2/Secrets
      - ~/Website2/templates:/Website2/templates
      - ~/Website2/requirements.txt:/Website2/requirements.txt
    networks:
      - mynetwork
    working_dir: /Website2
    env_file:
      - .env
    environment:
      - PYTHONPATH=/Website2/.venv/Lib/site-packages
      - WORKERES=4
      - KEYFILE_PATH=/Website2/Secrets/key_without_pass.pem
      - CERTFILE_PATH=/Website2/Secrets/Loveoffootball.crt
      - PYTHONDONTWRITEBYTECODE=1
    command: python src/run.py