version: '3.7'
networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
volumes:
  combined:
    external: true
  redis_data:
  frontend_data:
    driver: local
services:
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis_data:/data
    networks:
      - mynetwork
    ports:
      - 6379:6379
  backend:
    container_name: backend
    build:
      context: ./backend-container  # Updated path to backend-container directory
      dockerfile: Dockerfile.python
    image: python:3.9.18
    ports:
      - 5000:5000 
    volumes:
      - ./backend-container/src:/Website2/src  # Updated relative path for the src directory
      - ./Secrets:/Website2/Secrets
      - ./backend-container/requirements.txt:/Website2/requirements.txt  # Updated path to requirements.txt
    networks:
      - mynetwork
    working_dir: /Website2
    env_file:
      - .env
    environment:
      - PYTHONPATH=/Website2/.venv/Lib/site-packages
      - WORKERES=4
      - KEYFILE_PATH=/Website2/Secrets/key_without_pass.pem
      - CERTFILE_PATH=/Website2/Secrets/Loveoffootball.crt
      - PYTHONDONTWRITEBYTECODE=1
    command: python src/run.py
  frontend:
    container_name: frontend
    build:
      context: ./frontend-container  # Updated path to frontend-container directory
      dockerfile: Dockerfile.react
    ports:
      - 3000:3000
    networks:
      - mynetwork
    working_dir: /app
    volumes:
      - frontend_data:/app
