version: '3.7'

services:
  redis:
    image: redis:latest

  backend:
    image: loveofsports/python:3.9.18
    env_file:
      - production.env
    volumes:
      - ./backend-container/src:/ssweb/src:delegated

  frontend:
    image: loveofsports/ssweb-frontend:latest
    env_file:
      - production.env
    volumes:
      - ./frontend-container/:/app:delegated
      - /app/node_modules
