version: '3.7'

services:
  redis:
    environment:
      - REDIS_SERVICE_HOST=redis
      - REDIS_SERVICE_PORT=6379
  backend:
    environment:
      - DEBUG=True
      - NODE_ENV=development
      - BACKEND_SERVICE_HOST=backend 
      - BACKEND_SERVICE_PORT=5000
    volumes:
      - ./backend-container/src:/ssweb/src:delegated

  frontend:
    environment:
      - NODE_ENV=development
      - FRONTEND_SERVICE_HOST=frontend
      - FRONTEND_SERVICE_PORT=3000
    volumes:
      - ./jabascript/:/app:delegated
      - /app/node_modules
