apiVersion: apps/v1
kind: Deployment
metadata:
  name: feprod
  namespace: azdevspace
  labels:
    app: feprod
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: feprod
  template:
    metadata:
      labels:
        app: feprod
      annotations:
        date: "{{.Date}}"
    spec:
      containers:
        - name: feprod
          image: loveofsports.azurecr.io/fe:prodlatest
          imagePullPolicy: Always
          env:
            - name: FRONTEND_SERVICE_HOST
              value: frontend
            - name: FRONTEND_SERVICE_PORT
              value: "3000"
            - name: PUBLIC_ENV__NODE_ENV
              value: production
            - name: NODE_ENV
              value: production
            - name: BASE_URL
              valueFrom:
                secretKeyRef:
                  name: environment-urls
                  key: BASE_URL
            - name: API_URL
              valueFrom:
                secretKeyRef:
                  name: environment-urls
                  key: API_URL
            - name: LOG_URL
              valueFrom:
                secretKeyRef:
                  name: environment-urls
                  key: LOG_URL
            - name: AZURE_STORAGE_ACCOUNT
              value: sportfs
            - name: AZURE_STORAGE_KEY
              valueFrom:
                secretKeyRef:
                  name: azure-storage-account-secret
                  key: azurestorageaccountkey
            - name: AZURE_SHARE_NAME
              value: sportshare
            - name: REDIS_HOST
              value: "redis-service"
            - name: BACKEND_HOST
              value: "backend-service"
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: AUTH0_DOMAIN
            - name: ALGORITHMS
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: ALGORITHMS
            - name: API_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: API_AUDIENCE
            - name: AUTH0_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: AUTH0_SECRET
            - name: AUTH0_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: AUTH0_BASE_URL
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: AUTH0_CLIENT_ID
            - name: AUTH0_ISSUER_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: AUTH0_ISSUER_BASE_URL
            - name: VITE_AUTH0_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: AUTH0_SECRET
            - name: VITE_AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: AUTH0_DOMAIN
            - name: VITE_AUTH0_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: AUTH0_BASE_URL
            - name: VITE_AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: AUTH0_CLIENT_ID
            - name: AUTH0_ISSUER_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: AUTH0_ISSUER_BASE_URL
            - name: VITE_AUTH0_ISSUER_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: VITE_AUTH0_ISSUER_BASE_URL
            - name: VITE_SUPPORT_API_URL
              valueFrom:
                secretKeyRef:
                  name: environment-secret
                  key: VITE_SUPPORT_API_URL
            - name: VITE_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: VITE_PUBLISHABLE_KEY
            - name: VITE_BUY_BUTTON
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: VITE_BUY_BUTTON
            - name: VITE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: VITE_SECRET_KEY
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: google-auth-secrets
                  key: client_id
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-auth-secrets
                  key: client_secret
            - name: GOOGLE_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: google-auth-secrets
                  key: project_id
            - name: GOOGLE_AUTH_URI
              valueFrom:
                secretKeyRef:
                  name: google-auth-secrets
                  key: auth_uri
            - name: GOOGLE_TOKEN_URI
              valueFrom:
                secretKeyRef:
                  name: google-auth-secrets
                  key: token_uri
            - name: GOOGLE_AUTH_PROVIDER_X509_CERT_URL
              valueFrom:
                secretKeyRef:
                  name: google-auth-secrets
                  key: auth_provider_x509_cert_url
            - name: GOOGLE_REDIRECT_URIS
              valueFrom:
                secretKeyRef:
                  name: google-auth-secrets
                  key: redirect_uris
            - name: GOOGLE_JAVASCRIPT_ORIGINS
              valueFrom:
                secretKeyRef:
                  name: google-auth-secrets
                  key: javascript_origins
            - name: GOOGLE_APIKEY
              valueFrom:
                secretKeyRef:
                  name: google-auth-secrets
                  key: apikey
            - name: VITE_GOOGLE_APIKEY
              valueFrom:
                secretKeyRef:
                  name: google-auth-secrets
                  key: apikey
            - name: SENTRY_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: sentry-secrets
                  key: SENTRY_AUTH_TOKEN
            - name: VITE_NEWS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: news-api-key
                  key: VITE_NEWS_API_KEY
            - name: VITE_GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: google-client-id-secret
                  key: VITE_GOOGLE_CLIENT_ID
            - name: VITE_SENTRY_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: VITE_SENTRY_AUTH_TOKEN
            - name: VITE_APP_INSIGHTS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: app-insights-secrets
                  key: VITE_APP_INSIGHTS_CONNECTION_STRING
            - name: VITE_APP_INSIGHTS_KEY
              valueFrom:
                secretKeyRef:
                  name: app-insights-secrets
                  key: VITE_APP_INSIGHTS_KEY
            - name: VITE_APP_INSIGHTS_INSTRUMENTATION_KEY
              valueFrom:
                secretKeyRef:
                  name: app-insights-secrets
                  key: VITE_APP_INSIGHTS_INSTRUMENTATION_KEY
            - name: SENTRY_RELEASE
              valueFrom:
                secretKeyRef:
                  name: sentry-secrets
                  key: SENTRY_RELEASE
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /app/data
              name: fe-file-prod
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "2Gi"
      imagePullSecrets:
        - name: my-registry-secret
      volumes:
        - name: fe-file-prod
          persistentVolumeClaim:
            claimName: fe-pvc-prod
