apiVersion: v1
kind: PersistentVolume
metadata:
  name: fe-file-prod
spec:
  capacity:
    storage: 35Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storageclass
  azureFile:
    secretName: azure-storage-account-secret
    shareName: sportshare
    readOnly: false
