apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sp-rolebinding
  namespace: azdevspace
subjects:
- kind: User
  name: "b7d95cfe-542a-4116-ae52-c64bf13ded90"  # Application ID of the service principal
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit  # or another role that provides necessary permissions
  apiGroup: rbac.authorization.k8s.io

