apiVersion: apps/v1
kind: Deployment
metadata:
  name: be
  namespace: azdevspace
  labels:
    app: be
spec:
  replicas: 2
  imagePullPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: be
  template:
    metadata:
      labels:
        app: be
    spec:
      containers:
        - name: be
          image: loveofsports.azurecr.io/be:latest
          env:
            - name: BACKEND_SERVICE_HOST
              value: backend
            - name: BACKEND_SERVICE_PORT
              value: "5000"
            - name: NODE_ENV
              value: production
            - name: AZURE_STORAGE_ACCOUNT
              value: sportfs
            - name: AZURE_STORAGE_KEY
              valueFrom:
                secretKeyRef:
                  name: azure-storage-account-secret
                  key: azurestorageaccountkey
            - name: AZURE_SHARE_NAME
              value: sportshare
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: my-cluster-secrets
                  key: MONGODB_URL
            - name: REDIS_HOST
              value: "redis-service"
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /ssweb/backend-container
              name: backend-file
          resources:
            limits:
              cpu: "2"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "256Mi"
      imagePullSecrets:
        - name: my-registry-secret
      volumes:
        - name: backend-file
          persistentVolumeClaim:
            claimName: backend-pvc
