apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe
  namespace: azdevspace
  labels:
    app: fe
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      labels:
        app: fe
      annotations:
        date: "{{.Date}}"
    spec:
      containers:
        - name: fe
          image: loveofsports.azurecr.io/fe:latest
          imagePullPolicy: Always
          env:
            - name: FRONTEND_SERVICE_HOST
              value: frontend
            - name: FRONTEND_SERVICE_PORT
              value: "3000"
            - name: NODE_ENV
              value: production
            - name: AZURE_STORAGE_ACCOUNT
              value: sportfs
            - name: AZURE_STORAGE_KEY
              valueFrom:
                secretKeyRef:
                  name: azure-storage-account-secret
                  key: azurestorageaccountkey
            - name: AZURE_SHARE_NAME
              value: sportshare
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: my-cluster-secrets
                  key: MONGODB_URL
            - name: REDIS_HOST
              value: "redis-service"
            - name: BACKEND_HOST
              value: "backend-service"
            - name: VITE_COGNITO_USER_POOL_ID
              valueFrom:
                secretKeyRef:
                  name: cognito-config
                  key: VITE_COGNITO_USER_POOL_ID
            - name: VITE_COGNITO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: cognito-config
                  key: VITE_COGNITO_CLIENT_ID
            - name: VITE_AUTH0_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth0-secret
                  key: AUTH0_SECRET
            - name: VITE_AUTH0_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: auth0-secret
                  key: AUTH0_BASE_URL
            - name: VITE_AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auth0-secret
                  key: AUTH0_CLIENT_ID
            - name: VITE_AUTH0_ISSUER_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: auth0-secret
                  key: VITE_AUTH0_ISSUER_BASE_URL
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: AUTH0_DOMAIN
            - name: ALGORITHMS
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: ALGORITHMS
            - name: API_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: API_AUDIENCE
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /ssweb/frontend-container
              name: frontend-file
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "2"
              memory: "2Gi"
      imagePullSecrets:
        - name: my-registry-secret
      volumes:
        - name: frontend-file
          persistentVolumeClaim:
            claimName: frontend-pvc