apiVersion: apps/v1
kind: Deployment
metadata:
  name: be
  namespace: azdevspace
  labels:
    app: be
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: be
  template:
    metadata:
      labels:
        app: be
      annotations:
        date: "{{.Date}}"
    spec:
      containers:
        - name: be
          image: loveofsports.azurecr.io/be:latest
          imagePullPolicy: Always
          env:
            - name: R_LIBS_USER
              value: "/ssweb/backend-container/R/"
            - name: FLASK_DEBUG
              value: "false"
            - name: BACKEND_SERVICE_HOST
              value: backend
            - name: BACKEND_SERVICE_PORT
              value: "5000"
            - name: NODE_ENV
              value: production
            - name: AZURE_STORAGE_ACCOUNT
              value: sportfs
            - name: APP_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: APP_SECRET_KEY
            - name: AZURE_STORAGE_KEY
              valueFrom:
                secretKeyRef:
                  name: azure-storage-account-secret
                  key: azurestorageaccountkey
            - name: AZURE_SHARE_NAME
              value: sportshare
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: my-cluster-secrets
                  key: MONGODB_URL
            - name: REDIS_HOST
              value: "redis-service"
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: AUTH0_DOMAIN
            - name: ALGORITHMS
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: ALGORITHMS
            - name: API_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: API_AUDIENCE
            - name: AUTH0_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: AUTH0_SECRET
            - name: AUTH0_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: AUTH0_BASE_URL
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: AUTH0_CLIENT_ID
            - name: AUTH0_ISSUER_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: AUTH0_ISSUER_BASE_URL
            - name: VITE_AUTH0_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: VITE_AUTH0_SECRET
            - name: VITE_AUTH0_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: VITE_AUTH0_BASE_URL
            - name: VITE_AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: VITE_AUTH0_CLIENT_ID
            - name: VITE_AUTH0_ISSUER_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: auth0-secrets
                  key: VITE_AUTH0_ISSUER_BASE_URL
            - name: VITE_SUPPORT_API_URL
              valueFrom:
                secretKeyRef:
                  name: environment-secret 
                  key: VITE_SUPPORT_API_URL
            - name: DALLE3KEY
              valueFrom:
                secretKeyRef:
                  name: my-cluster-secrets
                  key: DALLE3KEY
            - name: OPENAI_ORGANIZATION
              valueFrom:
                secretKeyRef:
                  name: my-cluster-secrets
                  key: OPENAI_ORGANIZATION
            - name: FLASK_APP
              valueFrom:
                secretKeyRef:
                  name: my-cluster-secrets
                  key: FLASK_APP
            - name: FLASK_DEBUG
              valueFrom:
                secretKeyRef:
                  name: my-cluster-secrets
                  key: FLASK_DEBUG
            - name: WORKERS
              valueFrom:
                secretKeyRef:
                  name: my-cluster-secrets
                  key: WORKERS

          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /ssweb/backend-container
              name: backend-file
          resources:
            limits:
              cpu: "2"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "256Mi"
      imagePullSecrets:
        - name: my-registry-secret
      volumes:
        - name: backend-file
          persistentVolumeClaim:
            claimName: backend-pvc
