apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loveoffootball-ingress
  namespace: azdevspace
spec:
  defaultBackend:
    service:
      name: frontend-service
      port:
        number: 80
  ingressClassName: azure-application-gateway
  rules:
  - host: loveoffootball.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
  tls:
    - hosts:
        - loveoffootball.io
      secretName: loveoffootball-tls
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nwp-ingress-azdev
  namespace: azdevspace
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
    - Ingress
  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0