apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loveoffootball-ingress
  namespace: azdevspace
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - loveoffootball.io
    - www.loveoffootball.io
    secretName: loveoffootball-tls
  rules:
  - host: loveoffootball.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: frontend
            port:
              number: 3000
