apiVersion: v1
kind: Service
metadata:
  name: fetoaks
  namespace: azdevspace
spec:
  type: LoadBalancer
  selector:
    app: fetoaks
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000