apiVersion: v1
kind: Service
metadata:
  name: fe
  namespace: azdevspace
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
  - name: https
    port: 443
    targetPort: 3000
  selector:
    app: fe
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}