apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: azdevspace
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: loveofsports.azurecr.io/python:3.9.18
          env:
            - name: "DEBUG_DNS"
              value: "true"
            - name: BACKEND_SERVICE_HOST
              value: backend
            - name: BACKEND_SERVICE_PORT
              value: "5000"
            - name: DEBUG
              value: "True"
            - name: NODE_ENV
              value: development
            - name: AZURE_STORAGE_ACCOUNT
              value: sportfs
            - name: AZURE_STORAGE_KEY
              valueFrom:
                secretKeyRef:
                  name: azure-storage-account-secret
                  key: azurestorageaccountkey
            - name: AZURE_SHARE_NAME
              value: sportshare
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: my-cluster-secrets
                  key: MONGODB_URL
            - name: REDIS_HOST
              value: "redis-service"
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /ssweb/src
              name: sportfs
          resources:
            limits:
              cpu: "2"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "256Mi"
      imagePullSecrets:
        - name: my-registry-secret
      volumes:
        - name: sportfs
          persistentVolumeClaim:
            claimName: backend-pvc
