
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.azdev.yml
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.azdev.yml
        kompose.version: 1.21.0 (992df58d8)
      labels:
        io.kompose.service: backend
    spec:
      containers:
      - name: backend
        image: loveofsports.azurecr.io/python:3.9.18
        env:
        - name: BACKEND_SERVICE_HOST
          value: backend
        - name: BACKEND_SERVICE_PORT
          value: "5000"
        - name: DEBUG
          value: "True"
        - name: NODE_ENV
          value: development
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
            ephemeral-storage: "1Gi"
          requests:
            cpu: "500m"
            memory: "256Mi"
            ephemeral-storage: "500Mi"
        volumeMounts:
        - mountPath: /Website2/src
          name: backend-azdev0
      volumes:
      - name: backend-azdev0
        persistentVolumeClaim:
          claimName: backendpvc-azdev0
