apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: LoveofSports.azurecr.io/ssweb-frontend:latest
        env:
        - name: FRONTEND_SERVICE_HOST
          value: frontend
        - name: FRONTEND_SERVICE_PORT
          value: "3000"
        - name: NODE_ENV
          value: development
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /app
          name: frontendpvc-azdev1
        - mountPath: /app/node_modules
          name: frontendpvc-azdev0
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
      volumes:
      - name: frontendpvc-azdev1
        persistentVolumeClaim:
          claimName: frontendpvc-azdev1
      - name: frontendpvc-azdev0
        persistentVolumeClaim:
          claimName: frontendpvc-azdev0