#manifests/uat/ProjectStorage.yaml
# Define the StorageClass (shared with production)
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: storageclass  # Same as production
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard_LRS
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
  - debug
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
volumeBindingMode: Immediate
---

# Define the PersistentVolume (PV) for the frontend
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frontend-file-uat  # Distinguished for UAT
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 35Gi
  storageClassName: storageclass  # Same as production
  volumeMode: Filesystem
  azureFile:
    secretName: azure-storage-account-secret  # Same as production
    shareName: sportshare  # Same as production
---

# Define the PersistentVolume (PV) for the backend
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-file-uat  # Distinguished for UAT
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 35Gi
  storageClassName: storageclass  # Same as production
  volumeMode: Filesystem
  azureFile:
    secretName: azure-storage-account-secret  # Same as production
    shareName: sportshare  # Same as production
---

# Define the PersistentVolume (PV) for Redis
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-file-uat  # Distinguished for UAT
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 35Gi
  storageClassName: storageclass  # Same as production
  volumeMode: Filesystem
  azureFile:
    secretName: azure-storage-account-secret  # Same as production
    shareName: sportshare  # Same as production
---
# Ensure the same secret configuration is used if sharing the same Azure account
apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-account-secret  # Same as production
  namespace: uat
type: Opaque
data:
  azurestorageaccountkey: L0xMRjFKNE01d1RiZHZyQkY0QlhZRTJSbEpnTElhZUhQbmVkSzVzdFgxR1ZESWowTzVVK01mZjZjcXNwMWdYUlg4cm10ZmZiVTVteCtBU3RJZzhHbUE9PQ==
  azurestorageaccountname: c3BvcnRmcw==