apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lpkrestorationjob-binding-v2
  namespace: uat
subjects:
- kind: ServiceAccount
  name: lpkrestorationjob-v2
  namespace: uat
roleRef:
  kind: Role
  name: lpkrestorationjob-role-v2
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: routingmanager-rolebinding
  namespace: uat
subjects:
- kind: ServiceAccount
  name: routingmanager-sa # Replace with the actual service account name
  namespace: uat
roleRef:
  kind: Role
  name: routingmanager-role
  apiGroup: rbac.authorization.k8s.io
