apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: johnbonnett@loveoffootball.io
    privateKeySecretRef:
      name: letsencrypt-staging-private-key
    solvers:
    - http01:
        ingress:
          class: azure-application-gateway
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: loveoffootball-uat-tls
  namespace: uat
spec:
  secretName: loveoffootball-uat-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
  - uat.loveoffootball.io

