apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: your-tls-secret
  namespace: azdevspace
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: johnbonnett3@gmail.com # Replace with your email address
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
