apiVersion: v1
kind: Pod
metadata:
  namespace: azdevspace
  name: backend-pod
  labels:
    app: backend
spec:
  containers:
    - name: backend
      image: loveofsports.azurecr.io/python:3.9.18
      env:
        - name: "DEBUG_DNS"
          value: "true"
        - name: BACKEND_SERVICE_HOST
          value: backend
        - name: BACKEND_SERVICE_PORT
          value: "5000"
        - name: DEBUG
          value: "True"
        - name: NODE_ENV
          value: development
        - name: AZURE_STORAGE_ACCOUNT
          value: sportfs
        - name: AZURE_STORAGE_KEY
          valueFrom:
            secretKeyRef:
              name: azure-storage-account-secret
              key: azurestorageaccountkey
        - name: AZURE_SHARE_NAME
          value: sportshare
        - name: MONGODB_URL  # Add this environment variable
          valueFrom:
            secretKeyRef:
              name: my-cluster-secrets
              key: MONGODB_URL  # Use the correct key name
        - name: REDIS_HOST
          value: "redis-service"
      resources:
        limits:
          cpu: "2"
          memory: "1Gi"
        requests:
          cpu: "500m"
          memory: "256Mi"
      volumeMounts:
        - mountPath: /ssweb/src
          name: sportfs
  imagePullSecrets:
    - name: my-registry-secret
  volumes:
    - name: sportfs
      persistentVolumeClaim:
        claimName: backend-pvc

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend-pdb
  namespace: azdevspace
spec:
  minAvailable: 2  # Set the minimum available pods to 2 (to allow 1 disruption)
  selector:
    matchLabels:
      app: backend

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: azdevspace
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: backend
  type: ClusterIP
