apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
  namespace: azdevspace
spec:
  interval: 5m
  url: https://github.com/zepor/NFLSTATS.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: azdevspace
spec:
  interval: 10m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: podinfo
  path: ${{ secrets.KUSTOMIZE_PATH }}
  prune: true
  timeout: 1m