# Use an official Node runtime as a parent image
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /app

# Install any needed packages specified in package.json
COPY package.json package-lock.json ./
RUN npm install

# Bundle app source inside the Docker image
COPY . .

# Make port 3000 available to the world outside this container
EXPOSE 3000 9229

CMD ["node", "--inspect=0.0.0.0:9229", "debugkubernetes.js"]
