#frontend-container/docker-compose.prod.yml
services:
  feprod:
    container_name: frontend-prod-container
    build:
      context: .
      dockerfile: Dockerfile.Prod
      args:
        - NODE_ENV=production
    image: fe:prodlatest
    ports:
      - "3000:3000"
    networks:
      - prod-network
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PUBLIC_ENV__NODE_ENV=production
      - SOURCE_PATH=/app
      - NODE_OPTIONS=--max-old-space-size=12288
      - GIT_WORKFLOW=0 8
      - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
      - VITE_GOOGLE_APIKEY=${VITE_GOOGLE_APIKEY}
      - VITE_NEWS_API_KEY=${VITE_NEWS_API_KEY}
      - VITE_AUTH0_DOMAIN=${VITE_AUTH0_DOMAIN}
      - VITE_AUTH0_CLIENT_ID=${VITE_AUTH0_CLIENT_ID}
      - VITE_AUTH0_SECRET=${VITE_AUTH0_SECRET}
      - VITE_AUTH0_BASE_URL=${VITE_AUTH0_BASE_URL}
      - VITE_AUTH0_ISSUER_BASE_URL=${VITE_AUTH0_ISSUER_BASE_URL}
      - VITE_API_AUDIENCE=${VITE_API_AUDIENCE}
      - VITE_PUBLISHABLE_KEY=${VITE_PUBLISHABLE_KEY}
      - VITE_BUY_BUTTON=${VITE_BUY_BUTTON}
      - VITE_SECRET_KEY=${VITE_SECRET_KEY}
      - VITE_SUPPORT_API_URL=${VITE_SUPPORT_API_URL}
      - VITE_APP_INSIGHTS_KEY=${VITE_APP_INSIGHTS_KEY}
      - VITE_APP_INSIGHTS_CONNECTION_STRING=${VITE_APP_INSIGHTS_CONNECTION_STRING}
      - VITE_APP_INSIGHTS_INSTRUMENTATION_KEY=${VITE_APP_INSIGHTS_INSTRUMENTATION_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
      - GOOGLE_AUTH_URI=${GOOGLE_AUTH_URI}
      - GOOGLE_TOKEN_URI=${GOOGLE_TOKEN_URI}
      - GOOGLE_AUTH_PROVIDER_X509_CERT_URL=${GOOGLE_AUTH_PROVIDER_X509_CERT_URL}
      - GOOGLE_REDIRECT_URIS=${GOOGLE_REDIRECT_URIS}
      - GOOGLE_JAVASCRIPT_ORIGINS=${GOOGLE_JAVASCRIPT_ORIGINS}
      - GOOGLE_APIKEY=${GOOGLE_APIKEY}
      - BASE_URL=${BASE_URL}
      - API_URL=${API_URL}
      - LOG_URL=${LOG_URL}
    user: node
    stdin_open: true
    tty: true
networks:
  prod-network:
    driver: bridge
