#frontend-container/docker-compose.uat.yml
services:
  feuat:
    container_name: frontend-uat-container
    build:
      context: .
      dockerfile: Dockerfile.uat
    image: fe:uatlatest
    ports:
      - "3000:3000"
    networks:
      - uat-network
    volumes:
      - .:/app/:delegated
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PUBLIC_ENV__NODE_ENV=development
      - SOURCE_PATH=/app
      - NODE_OPTIONS=--max-old-space-size=12288
    user: node
    stdin_open: true
    tty: true
networks:
  uat-network:
