#KubernetesLocalProcessConfig.yaml
# kind: ConfigMap
# metadata:
#   name: bridge-to-kubernetes
# data:
#   kubernetesLocalProcessConfig.yaml: |
version: 0.1
env:
  - name: feuat
    value: feuat
  - name: DEBUG_MODE
    value: "true"
# volumes:
#   - name: app
#     mountPath: /app
# volumeMounts:
#   - name: default-token-*
#     localPath: /var/run/secrets/kubernetes.io/serviceaccount
# env:
#   - name: KUBERNETES_IN_CLUSTER_CONFIG_OVERRIDE
#     value: $(volumeMounts:default-token-*)

