apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  workspaceFolder: "/Website2"
  EEE: "/.env"
  DEBUG_MODE: "false"
  SECRET_KEY: "your_secret_key:"
  API_THROTTLE: "10"
  CERTFILE_PATH: "/Website2/Secrets/cert.pem"
  KEYFILE_PATH: "/Website2/Secrets/key_without_pass.pem"
  LOGFILE_PATH: "/Website2/Logs/Website2.log"
  CRTFILEPATH: "/Website2/Secrets/Loveoffootball.crt"
  PYTHONPATH: "/Website2/.venv/Lib/site-packages"
  WORKERS: "4"
  WEBDEST: "/Website2"
  DPP: "/Website2/.venv/Lib/site-packages"
  REDIS_HOST: "localhost"
  FLASK_ENV: "development"
  FLASK_APP: "src/app.py"
  MAVEN_OPTS: "-Xms1024m -Xmx3076m -XX:MaxPermSize=256m"
  REDIS_SERVICE_HOST: "172.16.238.3"
  REDIS_SERVICE_PORT: "6379"
  REDIS_PORT: "tcp://172.16.238.3:6379"
  REDIS_PORT_6379_TCP: "tcp://172.16.238.3:6379"
  REDIS_PORT_6379_TCP_PROTO: "tcp"
  REDIS_PORT_6379_TCP_PORT: "6379"
  REDIS_PORT_6379_TCP_ADDR: "172.16.238.3"
  WORKERES: "4"
  PYTHONDONTWRITEBYTECODE: "1"
  BACKENDEND_SERVICE_HOST: "172.16.238.2"
  BACKENDEND_SERVICE_PORT: "5000"
  BACKENDEND_PORT: "tcp://172.16.238.2:5000"
  BACKENDEND_PORT_5000_TCP: "tcp://172.16.238.2:5000"
  BACKENDEND_PORT_5000_TCP_PROTO: "tcp"
  BACKENDEND_PORT_5000_TCP_PORT: "5000"
  BACKENDEND_PORT_5000_TCP_ADDR: "172.16.238.2"
  NODE_ENV: "development"
  FRONTEND_SERVICE_HOST: "172.16.238.4"
  FRONTEND_SERVICE_PORT: "3000"
  FRONTEND_PORT: "tcp://172.16.238.4:3000"
  FRONTEND_PORT_3000_TCP: "tcp://172.16.238.4:3000"
  FRONTEND_PORT_3000_TCP_PROTO: "tcp"
  FRONTEND_PORT_3000_TCP_PORT: "3000"
  FRONTEND_PORT_3000_TCP_ADDR: "172.16.238.4"