# Define the StorageClass
kind: StorageClass

apiVersion: storage.k8s.io/v1
metadata:
  name: storeageclass
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
    kubernetes.io/cluster-service: "true"
provisioner: kubernetes.io/azure-file
parameters:
  skuName: Standard_LRS
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
  - debug
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
volumeBindingMode: Immediate
---

# Define the PersistentVolume (PV)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frontend-file
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 35Gi
  storageClassName: storageclass
  volumeMode: Filesystem
  azureFile:
    secretName: azure-storage-account-secret # Corrected name
    shareName: sportshare # Actual share name
---

# Define the PersistentVolume (PV)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backend-file
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 35Gi
  storageClassName: storageclass
  volumeMode: Filesystem
  azureFile:
    secretName: azure-storage-account-secret # Corrected name
    shareName: sportshare # Actual share name

---

# Define the PersistentVolume (PV)
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-file
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 35Gi
  storageClassName: storageclass
  volumeMode: Filesystem
  azureFile:
    secretName: azure-storage-account-secret # Corrected name
    shareName: sportshare # Actual share name
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-storage-account-secret 
  namespace: azdevspace
type: Opaque
data:
  azurestorageaccountkey: L0xMRjFKNE01d1RiZHZyQkY0QlhZRTJSbEpnTElhZUhQbmVkSzVzdFgxR1ZESWowTzVVK01mZjZjcXNwMWdYUlg4cm10ZmZiVTVteCtBU3RJZzhHbUE9PQ==
  azurestorageaccountname: c3BvcnRmcw==
