name: be
on:
  push:
    branches:
      - main
      - uat
  workflow_dispatch:

jobs:
  buildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Azure login
        uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      - name: Set image tag based on branch
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          if [[ "$BRANCH_NAME" == "main" ]]; then
            IMAGE_TAG="prod-latest"
          else
            IMAGE_TAG="uat-latest"
          fi
          echo "IMAGE_TAG=be:$IMAGE_TAG" >> $GITHUB_ENV
      - name: Build and push Docker image
        run: |
          docker build -t loveofsports.azurecr.io/be:${{ env.IMAGE_TAG }} -f backend-container/Dockerfile.python backend-container/
          docker push loveofsports.azurecr.io/be:${{ env.IMAGE_TAG }}
        env:
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
          AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
          ACR_RESOURCE_GROUP: ${{ secrets.ACR_RESOURCE_GROUP }}

  deploy:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs: buildImage
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      - uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ secrets.CLUSTER_NAME }}
          resource-group: ${{ secrets.CLUSTER_RESOURCE_GROUP }}
      - name: Prepare Deployment Manifest
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            manifest_dir="manifests/prod"
          else
            manifest_dir="manifests/uat"
          fi
          sed -i "s/{{.Date}}/$(date +%s)/" "${{ github.workspace }}/${manifest_dir}/deploy-be.yaml"
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ${{ github.workspace }}/${manifest_dir}/deploy-be.yaml
