name: fe
"on":
  push:
    branches:
      - main
  workflow_dispatch: {}
env:
  DEPLOYMENT_MANIFEST_PATH: |
    manifests/deploy-fe.yaml
    manifests/svc-fe.yaml
jobs:
  buildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
        name: Azure login
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      - name: Build and push image to ACR
        run: az acr build --image fe:latest --registry ${{ secrets.AZURE_CONTAINER_REGISTRY }} -g ${{ secrets.ACR_RESOURCE_GROUP }} -f frontend-container/Dockerfile.Prod frontend-container/
  deploy:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs: buildImage
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ secrets.CLUSTER_NAME }}
          resource-group: ${{ secrets.CLUSTER_RESOURCE_GROUP }}
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f manifests/deploy-fe.yaml
          kubectl apply -f manifests/svc-fe.yaml
