#fix
name: fe
"on":
  push:
    branches:
      - main
  workflow_dispatch: {}
env:
  DEPLOYMENT_MANIFEST_PATH: |
    manifests/deploy-fe.yaml
    manifests/svc-fe.yaml
jobs:
  buildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
        name: Azure login
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      - name: Build and push image to ACR
        run: |
          az acr build --registry ${{ secrets.AZURE_CONTAINER_REGISTRY }} --image fe:latest \
          --build-arg VITE_AUTH0_DOMAIN=${{ secrets.VITE_AUTH0_DOMAIN }} \
          --build-arg VITE_AUTH0_CLIENT_ID=${{ secrets.VITE_AUTH0_CLIENT_ID }} \
          --build-arg VITE_API_AUDIENCE=${{ secrets.VITE_API_AUDIENCE }} \
          --build-arg VITE_AUTH0_SECRET=${{ secrets.VITE_AUTH0_SECRET }} \
          --build-arg VITE_AUTH0_BASE_URL=${{ secrets.VITE_AUTH0_BASE_URL }} \
          --build-arg VITE_AUTH0_ISSUER_BASE_URL=${{ secrets.VITE_AUTH0_ISSUER_BASE_URL }} \
          --build-arg VITE_PUBLISHABLE_KEY=${{ secrets.VITE_PUBLISHABLE_KEY }} \
          --build-arg VITE_BUY_BUTTON=${{ secrets.VITE_BUY_BUTTON }} \
          --build-arg VITE_SECRET_KEY=${{ secrets.VITE_SECRET_KEY }} \
          --build-arg VITE_SUPPORT_API_URL=${{ secrets.VITE_SUPPORT_API_URL }} \
          -g ${{ secrets.ACR_RESOURCE_GROUP }} -f frontend-container/Dockerfile.Prod frontend-container/
  deploy:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs: buildImage
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
        name: Azure login
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      - uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ secrets.CLUSTER_NAME }}
          resource-group: ${{ secrets.CLUSTER_RESOURCE_GROUP }}
      - name: Prepare Deployment Manifest
        run: |
          DATE=$(date +%s)
          sed -i "s/{{.Date}}/$DATE/" manifests/deploy-fe.yaml
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f manifests/deploy-fe.yaml
          kubectl apply -f manifests/svc-fe.yaml
