#workflow/fe.yaml
name: fe 
on:
  push:
    branches:
      - main
      - uat
  workflow_dispatch:
jobs:
  buildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
        name: Azure login
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      - name: Build and push image to ACR
        env:
          VITE_COGNITO_USER_POOL_ID: ${{ secrets.VITE_COGNITO_USER_POOL_ID }}
          VITE_COGNITO_CLIENT_ID: ${{ secrets.VITE_COGNITO_CLIENT_ID }}
          VITE_AUTH0_DOMAIN: ${{ secrets.VITE_AUTH0_DOMAIN }}
          VITE_AUTH0_CLIENT_ID: ${{ secrets.VITE_AUTH0_CLIENT_ID }}
          VITE_API_AUDIENCE: ${{ secrets.VITE_API_AUDIENCE }}
          VITE_AUTH0_SECRET: ${{ secrets.VITE_AUTH0_SECRET }}
          VITE_AUTH0_BASE_URL: ${{ secrets.VITE_AUTH0_BASE_URL }}
          VITE_AUTH0_ISSUER_BASE_URL: ${{ secrets.VITE_AUTH0_ISSUER_BASE_URL }}
          VITE_PUBLISHABLE_KEY: ${{ secrets.VITE_PUBLISHABLE_KEY }}
          VITE_BUY_BUTTON: ${{ secrets.VITE_BUY_BUTTON }}
          VITE_SECRET_KEY: ${{ secrets.VITE_SECRET_KEY }}
          VITE_SUPPORT_API_URL: ${{ secrets.VITE_SUPPORT_API_URL }}
        run: |
          image_tag="${{ github.ref_name }}" == "main" ? "feprod" : "feuat"
          az acr build --registry ${{ secrets.AZURE_CONTAINER_REGISTRY }} \
                      --image ${{ secrets.AZURE_CONTAINER_REGISTRY }}/fe:$image_tag-latest \
                      --image ${{ secrets.AZURE_CONTAINER_REGISTRY }}/fe:$image_tag-$(date +%Y%m%d%H%M) \
                      -g ${{ secrets.ACR_RESOURCE_GROUP }} \
                      -f frontend-container/Dockerfile.Prod \
                      frontend-container/
  deploy:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs: buildImage
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
        name: Azure login
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      - uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ secrets.CLUSTER_NAME }}
          resource-group: ${{ secrets.CLUSTER_RESOURCE_GROUP }}
      - name: Prepare Deployment Manifest
        run: |
          manifest_dir="${{ github.ref_name }}" == "main" ? "manifests/prod" : "manifests/uat"
          sed -i "s/{{.Date}}/$(date +%s)/" ${{ github.workspace }}/${manifest_dir}/deploy-fe.yaml
      - name: Deploy to Kubernetes
        run: |
          manifest_dir="${{ github.ref_name }}" == "main" ? "manifests/prod" : "manifests/uat"
          kubectl apply -f ${{ github.workspace }}/${manifest_dir}/deploy-fe.yaml
          kubectl apply -f ${{ github.workspace }}/${manifest_dir}/svc-fe.yaml