name: Frontend Deployment
on:
  push:
    branches:
      - main
  workflow_dispatch: {}

env:
  ACR_RESOURCE_GROUP: LoveofSports-Dev
  AZURE_CONTAINER_REGISTRY: LoveofSports
  CHART_OVERRIDE_PATH: ./my-chart/values.yaml
  CHART_OVERRIDES: image.repository=LoveofSports.azurecr.io/loveofsports/ssweb-frontend,image.tag=${{ github.sha }}
  CHART_PATH: ./my-chart
  CLUSTER_NAME: DevCluster
  CLUSTER_RESOURCE_GROUP: LoveofSports-Dev
  CONTAINER_NAME: loveofsports/ssweb-frontend
  MANIFEST_PATHS: |
    manifests/frontend-pvc.yaml
    manifests/my-chart

jobs:
  buildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Build and push image to ACR
        run: az acr build --image ${{ env.CONTAINER_NAME }}:${{ github.sha }} --registry LoveofSports -g LoveofSports-Dev -f frontend-container/Dockerfile frontend-container/

  deploy:
    permissions:
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs: buildImage
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/use-kubelogin@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
      - name: Deploy application with Helm
        run: helm upgrade --install --wait -f ${{ env.CHART_OVERRIDE_PATH }} --set ${{ env.CHART_OVERRIDES }} automated-deployment ${{ env.CHART_PATH }} --namespace azdevspace
